### ISSUE TITLE
Random black tile on highlighted tile

### ISSUE THREAD

**Issue by Kamenuvol** [opentibiabr/otclient#596]
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

![image](https://github.com/mehah/otclient/assets/1878217/6a28696e-556a-4553-8976-11cc4d5589f8)

If you keep walking with highlight enabled it will bug like that. I suppose the thing is being deleted wrongly.

Tile::removeThing is using const TilePtr, maybe it's creating other shared pointer for same address and it gets deleted.
Also there is a comment "need refactoring" over it.
I reproduced it faster logging in, walk north/south with mouse lying on a wall with few sqm, logout and repeating.

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
Can you make a video on how to reproduce this?

**Comment by Riverlance** [comment]
> Can you make a video on how to reproduce this?

[![Mehah's OTClient - Black tile issue](https://i9.ytimg.com/vi_webp/NMDGrH3va_c/mq2.webp?sqp=CND13KgG-oaymwEmCMACELQB8quKqQMa8AEB-AH-CYACvAWKAgwIABABGFYgVChlMA8=&rs=AOn4CLAC3RR4TdYYkuSK1A9y_lTbr-yi6Q)](https://youtu.be/NMDGrH3va_c)

**Comment by mehah** [comment]
I thought it was a rendering problem, but no, It's protocol, here it works perfectly with TFS 1.3 1098 with
```c++
static constexpr int32_t NETWORKMESSAGE_MAXSIZE = 65500;
```

**Comment by mehah** [comment]
https://github.com/mehah/otclient/assets/2267386/15ab3870-334d-4935-98c3-47128bb4028b

**Comment by csantbr** [comment]
@mehah, that's the problem I've always talked about with you that's been making my life hell for a long time.

**Comment by mehah** [comment]
@csantbr 
but this problem is a protocol problem and not a client problem, if this doesn't happen on my server, there's nothing I can do.

**Comment by mehah** [comment]
I will not adapt the client to work on several versions of different servers, if they are using TFS 1.4 and this problem is occurring, the people who develop TFS should come and provide support for this, in the same way that the canary provides full support for servers maintained by them.

**Comment by csantbr** [comment]
@mehah, I don't think it's a protocol problem, because the same problem doesn't occur in the original OTClient versions and in OTClient V8, perhaps @conde2 can help us more deeply with this problem.

**Comment by mehah** [comment]
@csantbr 
but I'm talking about the reported problem, look at its log.

--
This problem with the tile disappearing only occurs here when it exceeds the protocol's size limit, when I place a very large extended screen.

**Comment by Kamenuvol** [comment]
It occurs only when HIGHLIGHT is enabled and always on the tile the pointer is on.

**Comment by mehah** [comment]
![image](https://github.com/mehah/otclient/assets/2267386/b28a2335-83a5-4125-9f96-2da5dcb5803e) = SERVER

**Comment by Riverlance** [comment]
Just tried again with the original code of 25th September 2023 (latest commit: [feat: QR Code support, with auto generate it from string](https://github.com/mehah/otclient/commit/14944377ab45bd7d774fa9a40e66cd187c6d3068)) with original TFS 1.5 (latest commit: [Support for hundredths after the decimal point (](https://github.com/otland/forgottenserver/commit/feda3fedf6f26218853736e6c36f7768f77012e4)https://github.com/otland/forgottenserver/pull/4524[)](https://github.com/otland/forgottenserver/commit/feda3fedf6f26218853736e6c36f7768f77012e4)) and protocol 12.87.

Then I changed the NETWORKMESSAGE_MAXSIZE to 65500 as you mentioned.
Still happening.

![image](https://github.com/mehah/otclient/assets/2280432/b5942fff-bd50-4adb-82e7-eaff93443ec7)

I forgot to mention that this issue is hard to make it to happen. It takes some time for it.

> ![image](https://user-images.githubusercontent.com/2267386/271733074-b28a2335-83a5-4125-9f96-2da5dcb5803e.png) = SERVER

Not sure if it's protocol, tbh. The errors on terminal I showed on the video appears only if you step in on the black tile. If don't do that, no errors shows up. Look:

![image](https://github.com/mehah/otclient/assets/2280432/111d7f0c-6f20-4fc6-9930-c6451eb250d4)

**Comment by Kamenuvol** [comment]
> ![image](https://user-images.githubusercontent.com/2267386/271733074-b28a2335-83a5-4125-9f96-2da5dcb5803e.png) = SERVER

Because you are moving to a tile that does not exist anymore in the client. The server sends you are moving there and the client does not found it. Read that function in src.

**Comment by mehah** [comment]
I managed to reproduce it. :)

**Comment by csantbr** [comment]
@mehah How?

**Comment by mehah** [comment]
> @mehah How?

like video

**Comment by mehah** [comment]
@Kamenuvol @Riverlance 
try now

**Comment by xrddw126** [comment]
I think that something is wrong with the highlight positioning now

**Comment by mehah** [comment]
> I think that something is wrong with the highlight positioning now

fixed

**Comment by KingOlafPrimeiro** [comment]
https://github.com/mehah/otclient/assets/147228488/276b66c1-51dc-4cd8-9e62-1953545ade62

i have same problem, but only in your otc....   otcv8 is normal

**Comment by csantbr** [comment]
@mehah This rendering problem still persists.

Apparently the creature may have died or been removed, but it hasn't been removed from the client, it still understands that the creature is there even though it doesn't exist.

![image](https://github.com/mehah/otclient/assets/61211407/c33376c3-5e40-41e8-8303-df613bedb10f)

**Comment by mehah** [comment]
@csantbr 
with highlight?

**Comment by csantbr** [comment]
@mehah Yes.

**Comment by mehah** [comment]
@csantbr test now
